### main library for data , read files,clean, built on numpy.
#### has dataframe and series - hod data of various types.

### series is column or row and are labeled

#### data frame is a 2 dimension labeled structure with rows and columns

In [34]:
import pandas as pd
import numpy as np

#### data structure in pandas:

#### In pandas we have 2 data structures that we are going to work with . 1 is Series and the other is Dataframe 
##### Series- is one dimentional labeled structures capable of holding data of any type.Basically it is a single row or column .
##### Dataframe-is a two dimensional labeled structure with rows and columns of potentially different data types, it is basically a table.

## Series

#### A Series is a one dimensional structure capable of holding data of any type(integers,string,float,python objects etc).
#### Series are the building block of dataframe. 
##### a series is basicaaly a single row or column 
### Creating a Series

In [35]:
a_list=[1,2,3,4,5,6,7,8,9]

a_series=pd.Series(a_list)

In [36]:
a_series

0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
8    9
dtype: int64

##### as seen in the output,the Series wraps both a sequence of values
##### and a sequenceof labels

In [37]:
a_series.ndim # to get the dimensions of a series we us (.ndim)

1

In [38]:
type(a_series) # to get the type of data u re using use(type(a_serie))

pandas.core.series.Series

#### Like with a Numpy array,data can be accessed by indexing[]
#### via the familiar python square-bracket notation:

In [39]:
a_series[0] # indexing to get the first item in our series.

#index the position

np.int64(1)

### Dataframe 
##### a  dataframe is a 2-dimension al labeled data structure with rows and columns 
##### of potentially different datatypes. it is a table.

### Creating a Dataframe from 2D Numpy array

In [40]:
a_arr=np.random.randint(1,100,50)

In [41]:
a_arr

array([57,  5, 54, 44,  9, 72, 10, 10,  3,  8, 86, 18,  1, 44, 11, 74, 44,
       40, 35, 55,  3, 42, 27,  4, 87, 32,  5,  3, 23, 63, 92, 50, 30, 49,
       67, 55, 80, 42, 66,  9, 12, 71,  2, 69, 26, 88, 42, 92, 53, 71],
      dtype=int32)

In [42]:
a_arr=a_arr.reshape(5,10) # reshape to get 2D array

In [43]:
a_arr

array([[57,  5, 54, 44,  9, 72, 10, 10,  3,  8],
       [86, 18,  1, 44, 11, 74, 44, 40, 35, 55],
       [ 3, 42, 27,  4, 87, 32,  5,  3, 23, 63],
       [92, 50, 30, 49, 67, 55, 80, 42, 66,  9],
       [12, 71,  2, 69, 26, 88, 42, 92, 53, 71]], dtype=int32)

In [44]:
#convert the 2D array above to a data frame:do as follow : we use
#dataframe function(df) from panda modules

df_a=pd.DataFrame(a_arr)

In [45]:
df_a

    0   1   2   3   4   5   6   7   8   9
0  57   5  54  44   9  72  10  10   3   8
1  86  18   1  44  11  74  44  40  35  55
2   3  42  27   4  87  32   5   3  23  63
3  92  50  30  49  67  55  80  42  66   9
4  12  71   2  69  26  88  42  92  53  71

In [46]:
# We can specify the row labels(index) and the column labels as follow:
pd.DataFrame(a_arr,index=['i','ii','iii','iv','v'],
             columns= ['A','B','C','D','E','F','G','H','I','J'])

      A   B   C   D   E   F   G   H   I   J
i    57   5  54  44   9  72  10  10   3   8
ii   86  18   1  44  11  74  44  40  35  55
iii   3  42  27   4  87  32   5   3  23  63
iv   92  50  30  49  67  55  80  42  66   9
v    12  71   2  69  26  88  42  92  53  71

### WE CAN CREATE A DATA FRAME FROM A DICTIONARY

In [47]:
dict={'County':['Nairobi', 'Mombasa', 'Nakuru', 'Turkana'], #
      'Population':[200000,3245765,458965,245674]}
# the values has to be equal in length,e,g we have 4 county,4 population.

In [48]:
dict

{'County': ['Nairobi', 'Mombasa', 'Nakuru', 'Turkana'],
 'Population': [200000, 3245765, 458965, 245674]}

In [49]:
pd.DataFrame(dict)

    County  Population
0  Nairobi      200000
1  Mombasa     3245765
2   Nakuru      458965
3  Turkana      245674

### CREATING A DATAFRAME BY READING IN CSV FILES

### most common ways of setting up a data frame is from
### reading an existing file.
###### the method used depend on the file being read in:
##### pd.read_csv()-csvfiles
##### pd.read_exel()
##### pd.read_pdf()
##### pd.read_html() html files and links

#### Panda takes care of any missing values when reading in data by using 
word NaN in any place of missing values unlike in the case of dictionary ,reading in files with missing values will not result in an error.

In [50]:
df=pd.read_csv('df.csv')# if your csv file is in the same directory(folder)
# as your notebook, no need to specify the full path of the file.

In [51]:
df

     County  Population   Area      count
0   Nairobi   4397073.0    704  4397073.0
1    Kisumu   1155574.0   2085  1155574.0
2   Mombasa   1208333.0    220  1208333.0
3   Bungoma   1670570.0   3024  1670570.0
4   Mandera    867457.0  25942   867457.0
5   Turkana    926976.0  68233   926976.0
6  Marsabit    459785.0  70944   459785.0
7     Nyeri    759164.0   3325   759164.0
8   Nairobi   4397073.0    704  4397073.0
9      Embu         NaN   2821        NaN

##### when files are not in your directory(folder) you will need to write the full path to it.
##### How paths are defined in pandas:

In [52]:
#df1=pd.read_csv('C:\\Users\\shiru\\Downloads\\df .csv') #single backslash
# doesnt work with pandas hence need to add another backlash,
# or use single / forwardslash.


df1=pd.read_csv('df.csv')


### Types of data
#### 1Categorical data(qualitative) which represent characteristis like person's gender(male or female,marital status )
#### 2,Numerical data(quantitative) can be descrete data(no.of pple in a class,test questions answered correctly and age),continous data can take any value weight,height,temparature,length )

### After reading on the file it is important to  inspect the data and get a feel of it

### Operations you do initially that helps gain an understanding of your  data, to know what it look like ie structure

In [53]:
### to see the first few rows,use:
df.head() # by default it will result in first 5 rows

    County  Population   Area      count
0  Nairobi   4397073.0    704  4397073.0
1   Kisumu   1155574.0   2085  1155574.0
2  Mombasa   1208333.0    220  1208333.0
3  Bungoma   1670570.0   3024  1670570.0
4  Mandera    867457.0  25942   867457.0

In [54]:
df.head(3) # u can specify how many lines of output you want

    County  Population  Area      count
0  Nairobi   4397073.0   704  4397073.0
1   Kisumu   1155574.0  2085  1155574.0
2  Mombasa   1208333.0   220  1208333.0

In [55]:
# for the last few lines, use:
df.tail()# this gives the last 5 rows as output

     County  Population   Area      count
5   Turkana    926976.0  68233   926976.0
6  Marsabit    459785.0  70944   459785.0
7     Nyeri    759164.0   3325   759164.0
8   Nairobi   4397073.0    704  4397073.0
9      Embu         NaN   2821        NaN

In [56]:
df.tail(2) # you can specify how many lines of output you want

    County  Population  Area      count
8  Nairobi   4397073.0   704  4397073.0
9     Embu         NaN  2821        NaN

You can as well get a sample row of a dataframe

In [57]:
df.sample()# You get 1 line of output selected randomly.

     County  Population   Area     count
6  Marsabit    459785.0  70944  459785.0

In [58]:
df.sample(4)# You can specify the number of lines of output you want

    County  Population   Area      count
2  Mombasa   1208333.0    220  1208333.0
4  Mandera    867457.0  25942   867457.0
9     Embu         NaN   2821        NaN
3  Bungoma   1670570.0   3024  1670570.0

### Get information about your dataframe 
#### use df.info()
we get the following information:
##### datatype we're dealing with
##### Number of rows we have
##### Total number of columns 
##### A breakdown of the columns,Number of entries and the datatype the column holds.

### Pandas dtype and their usage:
##### Object-Text or mixed numeric and non numeric values
##### int64:Integers numbers
##### Float64:Floating point numbers
##### Bool;True/false values

In [59]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   County      10 non-null     object
 1   Population  9 non-null      float64
 2   Area        10 non-null     int64
 3   count       9 non-null      float64
dtypes: float64(2), int64(1), object(1)
memory usage: 448.0+ bytes

In [60]:
df.columns # list of columns in your data

Index(['County', 'Population', 'Area', 'count'], dtype='object')

In [61]:
#index range 
df.index

RangeIndex(start=0, stop=10, step=1)

In [62]:
# values in the data in form of an array
df.values

array([['Nairobi', 4397073.0, 704, 4397073.0],
       ['Kisumu', 1155574.0, 2085, 1155574.0],
       ['Mombasa', 1208333.0, 220, 1208333.0],
       ['Bungoma', 1670570.0, 3024, 1670570.0],
       ['Mandera', 867457.0, 25942, 867457.0],
       ['Turkana', 926976.0, 68233, 926976.0],
       ['Marsabit', 459785.0, 70944, 459785.0],
       ['Nyeri', 759164.0, 3325, 759164.0],
       ['Nairobi', 4397073.0, 704, 4397073.0],
       ['Embu', nan, 2821, nan]], dtype=object)

In [63]:
# of of data in terms of rows and columns 
df.shape

(10, 4)

In [64]:
# dimensions of our data 
df.ndim

2

In [65]:
# get different datatypes in each column 
df.dtypes

County         object
Population    float64
Area            int64
count         float64
dtype: object

In [66]:
# get number of entries/values in each column :count works only on dataframe
# object
df.count()

County        10
Population     9
Area          10
count          9
dtype: int64

### STATISTICAL SUMMARY
#### We use method describe() -it returns a statistical summary of the numerical columns. in our case they are population,Area and count columns .

### Statistical summary of numerical columns

In [67]:
df.describe()

         Population          Area         count
count  9.000000e+00     10.000000  9.000000e+00
mean   1.760223e+06  17800.200000  1.760223e+06
std    1.531697e+06  28336.969742  1.531697e+06
min    4.597850e+05    220.000000  4.597850e+05
25%    8.674570e+05   1049.250000  8.674570e+05
50%    1.155574e+06   2922.500000  1.155574e+06
75%    1.670570e+06  20287.750000  1.670570e+06
max    4.397073e+06  70944.000000  4.397073e+06

In [68]:
# to get a mean of a given column e.g population: fist index population 
# column by using square braket and name of the column.['Population ']
# then append the statistical method whose value we wantto get ie .mean()
df['Population'].mean()

np.float64(1760222.7777777778)

In [69]:
# if you want to get the median of the area column:we index area column 
# and append median function 
df['Area'].median()

np.float64(2922.5)

In [70]:
df ['count'].mode()

0    4397073.0
Name: count, dtype: float64

In [71]:
df['Population'].std

<bound method Series.std of 0    4397073.0
1    1155574.0
2    1208333.0
3    1670570.0
4     867457.0
5     926976.0
6     459785.0
7     759164.0
8    4397073.0
9          NaN
Name: Population, dtype: float64>

### how to get statistical summary of categorical(text_type) column (they hold text values).
using the 'include' parameter assigne 'O'capital O' enables you to get a summary of categorical columns(which are of type object, thus O

In [72]:
df.describe(include='O')# 'O'is for object

         County
count        10
unique        9
top     Nairobi
freq          2

In [73]:
df

     County  Population   Area      count
0   Nairobi   4397073.0    704  4397073.0
1    Kisumu   1155574.0   2085  1155574.0
2   Mombasa   1208333.0    220  1208333.0
3   Bungoma   1670570.0   3024  1670570.0
4   Mandera    867457.0  25942   867457.0
5   Turkana    926976.0  68233   926976.0
6  Marsabit    459785.0  70944   459785.0
7     Nyeri    759164.0   3325   759164.0
8   Nairobi   4397073.0    704  4397073.0
9      Embu         NaN   2821        NaN

In [74]:
# to get the unique values in categorical columns first index the column 
# select the column you want to perform operation on. then append the unique
df['County'].unique()

array(['Nairobi', 'Kisumu', 'Mombasa', 'Bungoma', 'Mandera', 'Turkana',
       'Marsabit', 'Nyeri', 'Embu'], dtype=object)

In [75]:
# to get number of unique entries in a column by appending 
#fuction (.nunique ())
df['County'].nunique()

9

In [76]:
# to get summary of unique entries and number of times 
#they appear in column :first select the column 
#((county),then append .value_counts())
df['County'].value_counts()

County
Nairobi     2
Kisumu      1
Mombasa     1
Bungoma     1
Mandera     1
Turkana     1
Marsabit    1
Nyeri       1
Embu        1
Name: count, dtype: int64

### Missing values

#### Detecting missing values.
#### missing values in pandas are represented by NaN Keyword
###### they return a dataframe  filled with True or False depending on whether missing values are present in the respective cells or not

In [77]:
df.isna() # not appropriate to use when using large data.

   County  Population   Area  count
0   False       False  False  False
1   False       False  False  False
2   False       False  False  False
3   False       False  False  False
4   False       False  False  False
5   False       False  False  False
6   False       False  False  False
7   False       False  False  False
8   False       False  False  False
9   False        True  False   True

In [78]:
df.isnull()## when dealing with large data it will be had to detect
# missing values

   County  Population   Area  count
0   False       False  False  False
1   False       False  False  False
2   False       False  False  False
3   False       False  False  False
4   False       False  False  False
5   False       False  False  False
6   False       False  False  False
7   False       False  False  False
8   False       False  False  False
9   False        True  False   True

#### when dealing with large data we append other fuctions get a summary of null values.these fuctions are any(),all() or sum().

In [79]:
      # any() evaluates if there exist any null values in a column 
     # Returns True if there is a null value and False if there isnt.

df.isnull().any()

County        False
Population     True
Area          False
count          True
dtype: bool

In [80]:
df.isnull().all() # return True if all the values in column are missing or false if they're not .

County        False
Population    False
Area          False
count         False
dtype: bool

In [81]:
df.isnull().sum()# get a summarry of the number of the missing values in each column.
# this is the very best to use.

County        0
Population    1
Area          0
count         1
dtype: int64

#### How to deal with missing values
##### you can either replace null values with real values or drop them all together

## Drop missing values
#### if you want to get rid of missing values, use the dropna()method along with the axis argument.
###### by default,axis=index ie along row, meaning if any value within a row is missing 
###### ,then the whole row is droped. we can drop column by indicating axis as column.

In [82]:
df

     County  Population   Area      count
0   Nairobi   4397073.0    704  4397073.0
1    Kisumu   1155574.0   2085  1155574.0
2   Mombasa   1208333.0    220  1208333.0
3   Bungoma   1670570.0   3024  1670570.0
4   Mandera    867457.0  25942   867457.0
5   Turkana    926976.0  68233   926976.0
6  Marsabit    459785.0  70944   459785.0
7     Nyeri    759164.0   3325   759164.0
8   Nairobi   4397073.0    704  4397073.0
9      Embu         NaN   2821        NaN

In [83]:
df.dropna(axis='rows')# u can use 'index or row means the same' u drop the rows with missing values.

     County  Population   Area      count
0   Nairobi   4397073.0    704  4397073.0
1    Kisumu   1155574.0   2085  1155574.0
2   Mombasa   1208333.0    220  1208333.0
3   Bungoma   1670570.0   3024  1670570.0
4   Mandera    867457.0  25942   867457.0
5   Turkana    926976.0  68233   926976.0
6  Marsabit    459785.0  70944   459785.0
7     Nyeri    759164.0   3325   759164.0
8   Nairobi   4397073.0    704  4397073.0

In [84]:
df.dropna(axis='columns')# u drop the column with the missing values.

     County   Area
0   Nairobi    704
1    Kisumu   2085
2   Mombasa    220
3   Bungoma   3024
4   Mandera  25942
5   Turkana  68233
6  Marsabit  70944
7     Nyeri   3325
8   Nairobi    704
9      Embu   2821

### you can replace missing values with other values.
#### #we use fiilna()method to replace missing values with values we specify.this values could be specific like 0,
#### or a calculated value from sorrounding values or a guessed value or statistical value. 
#### it all depend on the data you are working with, and what's your end goal is.

In [85]:
df

     County  Population   Area      count
0   Nairobi   4397073.0    704  4397073.0
1    Kisumu   1155574.0   2085  1155574.0
2   Mombasa   1208333.0    220  1208333.0
3   Bungoma   1670570.0   3024  1670570.0
4   Mandera    867457.0  25942   867457.0
5   Turkana    926976.0  68233   926976.0
6  Marsabit    459785.0  70944   459785.0
7     Nyeri    759164.0   3325   759164.0
8   Nairobi   4397073.0    704  4397073.0
9      Embu         NaN   2821        NaN

In [86]:
df.fillna(0) # pass the value that you want to replace missing value with. in our case we use 0.
# where we had missing values had been replaced with 0.

     County  Population   Area      count
0   Nairobi   4397073.0    704  4397073.0
1    Kisumu   1155574.0   2085  1155574.0
2   Mombasa   1208333.0    220  1208333.0
3   Bungoma   1670570.0   3024  1670570.0
4   Mandera    867457.0  25942   867457.0
5   Turkana    926976.0  68233   926976.0
6  Marsabit    459785.0  70944   459785.0
7     Nyeri    759164.0   3325   759164.0
8   Nairobi   4397073.0    704  4397073.0
9      Embu         0.0   2821        0.0

In [87]:
# we can replace missing values with statistical values of our column which will b more accurate
# than using 0.eg replace missing value in the Population column with meadian of the population column.we index population,
df['Population'].fillna(df['Population'].median())# this operation doesn't change the original dataframe like seen below.

0    4397073.0
1    1155574.0
2    1208333.0
3    1670570.0
4     867457.0
5     926976.0
6     459785.0
7     759164.0
8    4397073.0
9    1155574.0
Name: Population, dtype: float64

In [ ]:
df # Population column row 9 is still NaN despite filling with median above.

     County  Population   Area      count
0   Nairobi   4397073.0    704  4397073.0
1    Kisumu   1155574.0   2085  1155574.0
2   Mombasa   1208333.0    220  1208333.0
3   Bungoma   1670570.0   3024  1670570.0
4   Mandera    867457.0  25942   867457.0
5   Turkana    926976.0  68233   926976.0
6  Marsabit    459785.0  70944   459785.0
7     Nyeri    759164.0   3325   759164.0
8   Nairobi   4397073.0    704  4397073.0
9      Embu         NaN   2821        NaN

In [89]:
# to ensure the opeartion is implimented in our dataframe we add  parameter (inplace=TRUE).it ensures that the operation has
# taken effect in our dataframe permanently . as follows.

df['Population'].fillna(df['Population'].median(),inplace=True)

In [90]:
df['Population'].fillna(df ['Population'].median(),inplace=True)

In [91]:
df # call the df, and realise the change in population column has taken effect.No missing values,

     County  Population   Area      count
0   Nairobi   4397073.0    704  4397073.0
1    Kisumu   1155574.0   2085  1155574.0
2   Mombasa   1208333.0    220  1208333.0
3   Bungoma   1670570.0   3024  1670570.0
4   Mandera    867457.0  25942   867457.0
5   Turkana    926976.0  68233   926976.0
6  Marsabit    459785.0  70944   459785.0
7     Nyeri    759164.0   3325   759164.0
8   Nairobi   4397073.0    704  4397073.0
9      Embu   1155574.0   2821        NaN

In [92]:
# following the above procedure, we can do for count now:

df['count'].fillna(df['count'].median(),inplace=True)

C:\Users\HP\AppData\Local\Temp\ipykernel_8668\2066293142.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['count'].fillna(df['count'].median(),inplace=True)

In [93]:
df # the median value has filled in the missing value in count columns as seen above.

     County  Population   Area      count
0   Nairobi   4397073.0    704  4397073.0
1    Kisumu   1155574.0   2085  1155574.0
2   Mombasa   1208333.0    220  1208333.0
3   Bungoma   1670570.0   3024  1670570.0
4   Mandera    867457.0  25942   867457.0
5   Turkana    926976.0  68233   926976.0
6  Marsabit    459785.0  70944   459785.0
7     Nyeri    759164.0   3325   759164.0
8   Nairobi   4397073.0    704  4397073.0
9      Embu   1155574.0   2821  1155574.0

### THE INPLACE PARAMETER
#### when inplace=false which is default setting,the operation is performed and returned a copy of the object (no change).
##### when inplace=True, the data is modified in place which means the dataframe will be updated. 
#### inplace parameter is used with the following:
#### dropna()
#### drop_duplicates()
#### fillna()
#### query()
#### rename()
#### reset_index()
#### sort_values()
#### sort_index()
#### drop()

### SUBSETTING AND SELECTING COLUMNS
##### use the indexing operator[ ]e.g df ['column_name'] is the most encouraged.

In [94]:
df

     County  Population   Area      count
0   Nairobi   4397073.0    704  4397073.0
1    Kisumu   1155574.0   2085  1155574.0
2   Mombasa   1208333.0    220  1208333.0
3   Bungoma   1670570.0   3024  1670570.0
4   Mandera    867457.0  25942   867457.0
5   Turkana    926976.0  68233   926976.0
6  Marsabit    459785.0  70944   459785.0
7     Nyeri    759164.0   3325   759164.0
8   Nairobi   4397073.0    704  4397073.0
9      Embu   1155574.0   2821  1155574.0

In [95]:
df['count'] # you want to select a certain column like county,say df['count'] .count values are displayed as shown.

0    4397073.0
1    1155574.0
2    1208333.0
3    1670570.0
4     867457.0
5     926976.0
6     459785.0
7     759164.0
8    4397073.0
9    1155574.0
Name: count, dtype: float64

In [96]:
df.County # dot notation not encouraged much.

0     Nairobi
1      Kisumu
2     Mombasa
3     Bungoma
4     Mandera
5     Turkana
6    Marsabit
7       Nyeri
8     Nairobi
9        Embu
Name: County, dtype: object

In [97]:
# selecting a column the data structure we get is usually a Series.eg if we select County column,
# ad do the type fuction it come out as series.
type(df['County'])

pandas.core.series.Series

In [98]:
##when you select muliple columns, you get a dataframe
df[['Area','County']]

    Area    County
0    704   Nairobi
1   2085    Kisumu
2    220   Mombasa
3   3024   Bungoma
4  25942   Mandera
5  68233   Turkana
6  70944  Marsabit
7   3325     Nyeri
8    704   Nairobi
9   2821      Embu

In [99]:
# there are some operations which you can carry out on dataframe and not in series coz 
# of the difference in the methods available.e,g if u want to make use of a method that belong to dataframe, but u want to apply
# that method to a single column series, u use a trick- make use of double square braket [[]] 
#to select a single column as a dataframe
df[['County']]

     County
0   Nairobi
1    Kisumu
2   Mombasa
3   Bungoma
4   Mandera
5   Turkana
6  Marsabit
7     Nyeri
8   Nairobi
9      Embu

### CREATING COLUMNS


#### creating columns in pandas is simple as indexing using the name of the column is supposed to have.
##### u can assing single value ,multiple values eg

### SINGLE RANDOM VALUE  - 
#### first index that name eg df['random']random is the name of our column then assign= value into it then run it.eg

In [100]:
df['Random']=4

In [101]:
df

     County  Population   Area      count  Random
0   Nairobi   4397073.0    704  4397073.0       4
1    Kisumu   1155574.0   2085  1155574.0       4
2   Mombasa   1208333.0    220  1208333.0       4
3   Bungoma   1670570.0   3024  1670570.0       4
4   Mandera    867457.0  25942   867457.0       4
5   Turkana    926976.0  68233   926976.0       4
6  Marsabit    459785.0  70944   459785.0       4
7     Nyeri    759164.0   3325   759164.0       4
8   Nairobi   4397073.0    704  4397073.0       4
9      Embu   1155574.0   2821  1155574.0       4

In [102]:
# create new columns and define the value it will hold.  we index the column,using the name it
## is supposed to have then assign value to it. we can assign values using a list.eg
df['Game Park']=['Yes','No','No','Yes','No','Yes','Yes','No','Yes','No']

In [103]:
df

     County  Population   Area      count  Random Game Park
0   Nairobi   4397073.0    704  4397073.0       4       Yes
1    Kisumu   1155574.0   2085  1155574.0       4        No
2   Mombasa   1208333.0    220  1208333.0       4        No
3   Bungoma   1670570.0   3024  1670570.0       4       Yes
4   Mandera    867457.0  25942   867457.0       4        No
5   Turkana    926976.0  68233   926976.0       4       Yes
6  Marsabit    459785.0  70944   459785.0       4       Yes
7     Nyeri    759164.0   3325   759164.0       4        No
8   Nairobi   4397073.0    704  4397073.0       4       Yes
9      Embu   1155574.0   2821  1155574.0       4        No

In [106]:
df['Random' ]== ['Game Park']=['Yes','No','No','Yes','No','Yes','Yes','No','Yes','No']

SyntaxError: cannot assign to comparison (555803195.py, line 1)

In [107]:
## Create a new column from mathematical operation between two column 

# eg creat a new column called density whose values will b a result of Population column and area column.
# we calculate the Population density. we do these:
    
df['Density']=df['Population']/df['Area']

In [ ]:
df

In [108]:
# if you want to round of your valuesto a cetain decimal points we use round() fuction like below, we will round 
# density column.then pass number of decimal point u want to round off to.inour case 2

round(df['Density'],2)

0    6245.84
1     554.23
2    5492.42
3     552.44
4      33.44
5      13.59
6       6.48
7     228.32
8    6245.84
9     409.63
Name: Density, dtype: float64

In [109]:
df

     County  Population   Area      count  Random Game Park      Density
0   Nairobi   4397073.0    704  4397073.0       4       Yes  6245.842330
1    Kisumu   1155574.0   2085  1155574.0       4        No   554.232134
2   Mombasa   1208333.0    220  1208333.0       4        No  5492.422727
3   Bungoma   1670570.0   3024  1670570.0       4       Yes   552.437169
4   Mandera    867457.0  25942   867457.0       4        No    33.438324
5   Turkana    926976.0  68233   926976.0       4       Yes    13.585450
6  Marsabit    459785.0  70944   459785.0       4       Yes     6.480957
7     Nyeri    759164.0   3325   759164.0       4        No   228.320000
8   Nairobi   4397073.0    704  4397073.0       4       Yes  6245.842330
9      Embu   1155574.0   2821  1155574.0       4        No   409.632754

In [110]:
# no change after rounding of , what we do to get permanent change in our dataframe is to reassign the values of the density

# we say: 

df['Density']=round(df['Density'],2)

In [111]:
df

     County  Population   Area      count  Random Game Park  Density
0   Nairobi   4397073.0    704  4397073.0       4       Yes  6245.84
1    Kisumu   1155574.0   2085  1155574.0       4        No   554.23
2   Mombasa   1208333.0    220  1208333.0       4        No  5492.42
3   Bungoma   1670570.0   3024  1670570.0       4       Yes   552.44
4   Mandera    867457.0  25942   867457.0       4        No    33.44
5   Turkana    926976.0  68233   926976.0       4       Yes    13.59
6  Marsabit    459785.0  70944   459785.0       4       Yes     6.48
7     Nyeri    759164.0   3325   759164.0       4        No   228.32
8   Nairobi   4397073.0    704  4397073.0       4       Yes  6245.84
9      Embu   1155574.0   2821  1155574.0       4        No   409.63

### DROP COLUMNS
#### we use method drop(),we have to specify the axis on which methodd should operate.For
#### rows specify axis='rows' (which is default), for columns specify -axis=column

In [112]:
df.drop('Random',axis='columns')

     County  Population   Area      count Game Park  Density
0   Nairobi   4397073.0    704  4397073.0       Yes  6245.84
1    Kisumu   1155574.0   2085  1155574.0        No   554.23
2   Mombasa   1208333.0    220  1208333.0        No  5492.42
3   Bungoma   1670570.0   3024  1670570.0       Yes   552.44
4   Mandera    867457.0  25942   867457.0        No    33.44
5   Turkana    926976.0  68233   926976.0       Yes    13.59
6  Marsabit    459785.0  70944   459785.0       Yes     6.48
7     Nyeri    759164.0   3325   759164.0        No   228.32
8   Nairobi   4397073.0    704  4397073.0       Yes  6245.84
9      Embu   1155574.0   2821  1155574.0        No   409.63

In [113]:
df # the randon column is still there. we need to use(inplace=true) to ensure the random 
# column is completely dropped .

     County  Population   Area      count  Random Game Park  Density
0   Nairobi   4397073.0    704  4397073.0       4       Yes  6245.84
1    Kisumu   1155574.0   2085  1155574.0       4        No   554.23
2   Mombasa   1208333.0    220  1208333.0       4        No  5492.42
3   Bungoma   1670570.0   3024  1670570.0       4       Yes   552.44
4   Mandera    867457.0  25942   867457.0       4        No    33.44
5   Turkana    926976.0  68233   926976.0       4       Yes    13.59
6  Marsabit    459785.0  70944   459785.0       4       Yes     6.48
7     Nyeri    759164.0   3325   759164.0       4        No   228.32
8   Nairobi   4397073.0    704  4397073.0       4       Yes  6245.84
9      Embu   1155574.0   2821  1155574.0       4        No   409.63

In [ ]:

df.drop('Random',axis='columns',inplace=True) # apply like that

In [ ]:
df # random column id dropped now.

In [ ]:
# work with a certain set of columns and still want to preserve the original dataframe, u just
# create a variable lke: eg u want to work without Area column, drop it
df_no_area=df.drop('Area', axis= 'columns' )

In [ ]:
df_no_area    # this is a dataframe with no area.

In [ ]:
df # this is original dataframe.

## DELETE FUCTION as a way of dropping columns.
#### delete keyword is Del.

In [ ]:
# u can drop a columns by use of delete function
# say del , select the column you want to delete .eg game park column and index that. when u run it the column will b deleted.

del df['Game Park']

In [ ]:
df

### SELECTING AND SUBSETTING ROWS 
### Using iloc and loc u can do practically any data selection task on panda dataframes.
### df .loc[ ] is used to subset rows using explicit labels whereas df.iloc[ ] is used to subset rows using implicit  python style index/integer positional values.
### df.loc[ ]

### loc[..]
#### Acessess a group of rows and columns by labels. We can FILTER data using the loc[ ] fuction even if the indicesare not integers.

In [114]:
df

     County  Population   Area      count  Random Game Park  Density
0   Nairobi   4397073.0    704  4397073.0       4       Yes  6245.84
1    Kisumu   1155574.0   2085  1155574.0       4        No   554.23
2   Mombasa   1208333.0    220  1208333.0       4        No  5492.42
3   Bungoma   1670570.0   3024  1670570.0       4       Yes   552.44
4   Mandera    867457.0  25942   867457.0       4        No    33.44
5   Turkana    926976.0  68233   926976.0       4       Yes    13.59
6  Marsabit    459785.0  70944   459785.0       4       Yes     6.48
7     Nyeri    759164.0   3325   759164.0       4        No   228.32
8   Nairobi   4397073.0    704  4397073.0       4       Yes  6245.84
9      Embu   1155574.0   2821  1155574.0       4        No   409.63

In [115]:
# # say we want to select first row in our data, say df.loc[] indicate the row label inside the [] (0-9) ar the row labels.
#it will be df.loc[0]. this is a series
df.loc[0]

County          Nairobi
Population    4397073.0
Area                704
count         4397073.0
Random                4
Game Park           Yes
Density         6245.84
Name: 0, dtype: object

In [116]:
# u can b able to select a single row as a data frame by using double [[]].
df.loc[[0]]

    County  Population  Area      count  Random Game Park  Density
0  Nairobi   4397073.0   704  4397073.0       4       Yes  6245.84

In [117]:
# to get a clear concept of how the loc[] method work, we're going to change the index value of our data. we set 
# County column as our new index.
# save the this operation in a new variable called df_c=df.set_index('County')
df_c=df.set_index('County')

In [118]:
# remember index and label means the same.

df_c    # county column is our new index. county names is our labels.

          Population   Area      count  Random Game Park  Density
County
Nairobi    4397073.0    704  4397073.0       4       Yes  6245.84
Kisumu     1155574.0   2085  1155574.0       4        No   554.23
Mombasa    1208333.0    220  1208333.0       4        No  5492.42
Bungoma    1670570.0   3024  1670570.0       4       Yes   552.44
Mandera     867457.0  25942   867457.0       4        No    33.44
Turkana     926976.0  68233   926976.0       4       Yes    13.59
Marsabit    459785.0  70944   459785.0       4       Yes     6.48
Nyeri       759164.0   3325   759164.0       4        No   228.32
Nairobi    4397073.0    704  4397073.0       4       Yes  6245.84
Embu       1155574.0   2821  1155574.0       4        No   409.63

In [119]:
df_c.loc['Nairobi']

         Population  Area      count  Random Game Park  Density
County
Nairobi   4397073.0   704  4397073.0       4       Yes  6245.84
Nairobi   4397073.0   704  4397073.0       4       Yes  6245.84

### SELECT MULTIPLE ROWS AND COLUMNS

In [120]:
# we can select multiple rows and columns using loc[] .example you want to
# get the population value of kisumu ,mombasa and bungoma. what u do:

#df_c.loc[['row_labels'],columns_labels]

df_c.loc[['Kisumu','Mombasa','Bungoma']]  # to get specific column u pass column label eg Population,density etc.

         Population  Area      count  Random Game Park  Density
County
Kisumu    1155574.0  2085  1155574.0       4        No   554.23
Mombasa   1208333.0   220  1208333.0       4        No  5492.42
Bungoma   1670570.0  3024  1670570.0       4       Yes   552.44

In [121]:
# to get specific column u pass column label eg Population,density 
df_c.loc[['Kisumu','Mombasa','Bungoma'],['Population','Density']]

         Population  Density
County
Kisumu    1155574.0   554.23
Mombasa   1208333.0  5492.42
Bungoma   1670570.0   552.44

In [122]:
df

     County  Population   Area      count  Random Game Park  Density
0   Nairobi   4397073.0    704  4397073.0       4       Yes  6245.84
1    Kisumu   1155574.0   2085  1155574.0       4        No   554.23
2   Mombasa   1208333.0    220  1208333.0       4        No  5492.42
3   Bungoma   1670570.0   3024  1670570.0       4       Yes   552.44
4   Mandera    867457.0  25942   867457.0       4        No    33.44
5   Turkana    926976.0  68233   926976.0       4       Yes    13.59
6  Marsabit    459785.0  70944   459785.0       4       Yes     6.48
7     Nyeri    759164.0   3325   759164.0       4        No   228.32
8   Nairobi   4397073.0    704  4397073.0       4       Yes  6245.84
9      Embu   1155574.0   2821  1155574.0       4        No   409.63

In [123]:
## to get population of madera.use of row labels and column labels

df.loc[4,'Population']

np.float64(867457.0)

In [ ]:
### RANGE SELECTION USING LOC[ ]
# for example u want to select (row no,2 all the to5) do this: 
df.loc[2:5]

In [124]:
# select a range of column:population to count
df.loc[:,'Population':'count']

   Population   Area      count
0   4397073.0    704  4397073.0
1   1155574.0   2085  1155574.0
2   1208333.0    220  1208333.0
3   1670570.0   3024  1670570.0
4    867457.0  25942   867457.0
5    926976.0  68233   926976.0
6    459785.0  70944   459785.0
7    759164.0   3325   759164.0
8   4397073.0    704  4397073.0
9   1155574.0   2821  1155574.0

## iloc[ ] is position based.
### used to subset rows or even columns using positional index(labels) values.This takes us back to what we had in Python.

In [125]:
df

     County  Population   Area      count  Random Game Park  Density
0   Nairobi   4397073.0    704  4397073.0       4       Yes  6245.84
1    Kisumu   1155574.0   2085  1155574.0       4        No   554.23
2   Mombasa   1208333.0    220  1208333.0       4        No  5492.42
3   Bungoma   1670570.0   3024  1670570.0       4       Yes   552.44
4   Mandera    867457.0  25942   867457.0       4        No    33.44
5   Turkana    926976.0  68233   926976.0       4       Yes    13.59
6  Marsabit    459785.0  70944   459785.0       4       Yes     6.48
7     Nyeri    759164.0   3325   759164.0       4        No   228.32
8   Nairobi   4397073.0    704  4397073.0       4       Yes  6245.84
9      Embu   1155574.0   2821  1155574.0       4        No   409.63

In [126]:
## if u want to select a row at position 3 bungoma  when run gives us row at position 3. # this is 
df.iloc[3]

County          Bungoma
Population    1670570.0
Area               3024
count         1670570.0
Random                4
Game Park           Yes
Density          552.44
Name: 3, dtype: object

In [127]:
## u want to get row as a datatframe use [[]], use double square bracket.
df.iloc[[3]]

    County  Population  Area      count  Random Game Park  Density
3  Bungoma   1670570.0  3024  1670570.0       4       Yes   552.44

In [128]:
# to get population of Bungoma start by the position of the row which is 3 and then position of the POpulation
# which is 1
df.iloc[3,1]

np.float64(1670570.0)

In [129]:
# select from Bungoma to Marsabit
df.iloc[3:7]

     County  Population   Area      count  Random Game Park  Density
3   Bungoma   1670570.0   3024  1670570.0       4       Yes   552.44
4   Mandera    867457.0  25942   867457.0       4        No    33.44
5   Turkana    926976.0  68233   926976.0       4       Yes    13.59
6  Marsabit    459785.0  70944   459785.0       4       Yes     6.48

In [130]:
df_c

          Population   Area      count  Random Game Park  Density
County
Nairobi    4397073.0    704  4397073.0       4       Yes  6245.84
Kisumu     1155574.0   2085  1155574.0       4        No   554.23
Mombasa    1208333.0    220  1208333.0       4        No  5492.42
Bungoma    1670570.0   3024  1670570.0       4       Yes   552.44
Mandera     867457.0  25942   867457.0       4        No    33.44
Turkana     926976.0  68233   926976.0       4       Yes    13.59
Marsabit    459785.0  70944   459785.0       4       Yes     6.48
Nyeri       759164.0   3325   759164.0       4        No   228.32
Nairobi    4397073.0    704  4397073.0       4       Yes  6245.84
Embu       1155574.0   2821  1155574.0       4        No   409.63

In [131]:
# want to select the column that have mandera  count to the position that has mandera is 4
#when u run you get the row at position 4 which has mandera county.
df_c.iloc[[4]] # dataframe

         Population   Area     count  Random Game Park  Density
County
Mandera    867457.0  25942  867457.0       4        No    33.44

In [132]:
df_c.iloc[4] # series

Population    867457.0
Area             25942
count         867457.0
Random               4
Game Park           No
Density          33.44
Name: Mandera, dtype: object

In [134]:
 # # when you want to select a row from Bungoma to marsabit start position is 3 bungoma  and stop position 6 marsabit but 
## for iloc it uses the other range selection in python. so the stop value has to be increased by one.

df.iloc[3  : 7]

     County  Population   Area      count  Random Game Park  Density
3   Bungoma   1670570.0   3024  1670570.0       4       Yes   552.44
4   Mandera    867457.0  25942   867457.0       4        No    33.44
5   Turkana    926976.0  68233   926976.0       4       Yes    13.59
6  Marsabit    459785.0  70944   459785.0       4       Yes     6.48

In [135]:



df

     County  Population   Area      count  Random Game Park  Density
0   Nairobi   4397073.0    704  4397073.0       4       Yes  6245.84
1    Kisumu   1155574.0   2085  1155574.0       4        No   554.23
2   Mombasa   1208333.0    220  1208333.0       4        No  5492.42
3   Bungoma   1670570.0   3024  1670570.0       4       Yes   552.44
4   Mandera    867457.0  25942   867457.0       4        No    33.44
5   Turkana    926976.0  68233   926976.0       4       Yes    13.59
6  Marsabit    459785.0  70944   459785.0       4       Yes     6.48
7     Nyeri    759164.0   3325   759164.0       4        No   228.32
8   Nairobi   4397073.0    704  4397073.0       4       Yes  6245.84
9      Embu   1155574.0   2821  1155574.0       4        No   409.63

In [136]:
df.iloc [3 :7]

     County  Population   Area      count  Random Game Park  Density
3   Bungoma   1670570.0   3024  1670570.0       4       Yes   552.44
4   Mandera    867457.0  25942   867457.0       4        No    33.44
5   Turkana    926976.0  68233   926976.0       4       Yes    13.59
6  Marsabit    459785.0  70944   459785.0       4       Yes     6.48

In [137]:
# u can also do back selection .e,g u want to select the last item in the data frame(-1) so
df.iloc[-1]

County             Embu
Population    1155574.0
Area               2821
count         1155574.0
Random                4
Game Park            No
Density          409.63
Name: 9, dtype: object

In [138]:
## when we use loc in -1 we get errors because-1 is not a label in the data

### MERGING
#### Situation will arise where you need to combine data from various sources. use the merge method to do so.¶

In [ ]:
# first decide the name you will give the file and is census_population _households

population=pd.read_excel('census population households.xlsx',thousands=',')

In [ ]:
population

In [ ]:

# # do a check on the data to b familiar with it.# THIS is the first thing u do with the data 
# call the info() method  once we run it we'll get more infomation about the data
population.info()

In [ ]:
##the reason for population is a numerical columns  and household have object as Dtype is coz of the coma separator
#as it makes numerical valu  to be a string value in pandas. 
#this affects the kind of operation, to get rid off them(coma separators),by including thousand parameters
#when reading the file add(thousands=',')

In [ ]:
population

In [ ]:
# check on the of the missing value
population.isnull().sum()

In [ ]:


# replace missing value with (0, inplace=True)
population.fillna(0, inplace=True)

In [ ]:
population .info()

In [ ]:
population.isnull().sum() # no missing  values now after filling with (0 and inplace=True)

In [ ]:
## Next is to convert the 2 columns household and population into integer values
# presence of null values convert integers into float values. 
# we use the  astype() method.first subset
# indexing the column we want to change (population)column, append the astype method then the change u want ('int')

population['Population'].astype('int')

In [ ]:
 # # the values are still  float values even after applying astype method
# what u do next is to reassign the values generated in the above operation by indexing the population
# column and use = for assignment

population['Population']=population['Population'].astype('int')

In [ ]:
 # after assigning the values Population has
# changed from float to integers as shown below. even Households as it is calculated below.
population.info()

In [ ]:

population['Households']=population['Households'].astype('int') # if u want to convert to float, .astype('float')

In [ ]:
# same indexing household column just like population u can use numpy as below

population['Households'] =population['Households'].astype(np.int64)   #or (# or np.float64 )
population .info()

In [ ]:
population

In [ ]:

population.info()

In [ ]:
# read in another file

In [ ]:
area=pd.read_excel('census area density.xlsx',thousands =',')

FileNotFoundError: [Errno 2] No such file or directory: 'census area density.xlsx'

In [ ]:

area

In [ ]:
# use differnt methods to get  familiar with the data. we will use head to get the first 5.
area.head()

In [ ]:
area.info()

In [ ]:
# check any null/missing values 
area.isnull().sum()

In [ ]:
# check any null/missing values 
area.isnull().sum()

In [ ]:
## check any null/missing values 
area.isnull().sum()

In [ ]:
area

In [ ]:
population

In [ ]:
# now all is set to combine the (area table and population table.)# use merge operation.
# census is the table that will result/carry the merge.

In [ ]:
# combine the two. do merge operation where we use merger fuction to carry out this operation
#census will carry the merged data. say pd.merge in there start with the table whose value u want to appear on the left side
#we want population b left and area b right. then define a common column which will be shared eg sub county which is occuring in
#both tables

census =pd.merge(population, area, on='Sub County')

In [ ]:
census

## GROUPBY

In [ ]:
# is used to arrange/ group identical data into groups using specified columns e.g if a particular column
# has identical entries in different rows then it will put these rows in one group.
#Group by single column is to place all rows with same value of only that particular column in one group.
# Groupby multiple columns is to place all rows with same value of both columns in one group.eg column 1+column 2 together .

In [ ]:
#Group by multiple columns means to place all the rows with the same value of both the column1 and column 2 in one group
#Groupby method works with aggregate fuctionss to give us meaningful results,by itself
# it is useless.Example of aggregate fuctions
#sum(): sum of group values is the most important 
#mean()mean of groups
#size():compute group sizes
#count():compute count of groups
#std():standard deviation of groups
#var()variance
#sem() std error of the mean of the groups
#describe()generate descriptive statistics 
#first() first of group values
#last()last of group values
#nth()takes the n value,or a subset if n is a list
#min()mean of group values
#max()max of group values.

In [ ]:
# we want to group the merged dataframe by counties so we can generate county level aggregates.

In [ ]:
# combine different  entries based on their county. use census data to aggregate all entries from a certain county together
#say census .groupby(' ')pass the column in which the aggregate is to b performed on.e.g county coz we want
#all the entries with the same county name to be combined. then use sum ()fuction.
census.groupby('County')
census

In [ ]:
census.groupby('County')

In [ ]:
census.groupby('County').sum()  # this will combine different entries under the same county ad sumup the different numerical
                                  #values with the same county

In [ ]:
# index/ row labels is usually based on the column used to do the groupby.if u want the column to b part of the data frame,
# append the reset_index() to the operation.eg which replace the column index into numerical index.

census.groupby('County').sum().reset_index()

#after you run, the new index/row labels (0,1,2,3) appear


### SORTING 
### Use sort_values() method

In [ ]:
# if sorting data with numerical columns, u haave to pass in a column name  to the by parameter,otherwise an errorr 
#will be generated.pandas need to know on whichever date/ column to perform the sorting
# to sort your values in a cetain order we use sort_value method . it will rearrange the position of values in 
#descending or ascending order.

In [ ]:
Census_grouped= census.groupby('County').sum().reset_index()

In [ ]:
Census_grouped

In [ ]:
Census_grouped.sort_values(by='Population') # means we are sorting by population. from the lowest populated area to the highest
# (default setting ) sort_value() sort by ascending order.

In [ ]:
 # want the index values to maintain order as before sorting.
  #  to do that we add reset_index() when we run a new index is included in the left side as follows 

Census_grouped.sort_values(by='Population').reset_index()

In [ ]:
# the problem now is the old disorganised index is still on the table. to remove it:
# in reset_index(drop=True) pass drop=True.

Census_grouped.sort_values(by='Population').reset_index(drop=True) # sorts in ascending-lowest to highest. to change this,
there argument you pass inside sort_values(ascending=False) ascending and give it the value False

In [ ]:
# sorts in ascending-lowest to highest. to change this,
# there argument you pass inside sort_values(ascending=False) ascending and give it the value False like these:

Census_grouped.sort_values(by='Population',ascending=False).reset_index(drop=True)

In [ ]:
# if u want to get the top 10 values/countys with highest population 
# include the head() method. inside the head() you specify the number of top values that you want to get.eg .head(10)

Census_grouped.sort_values(by='Population',ascending=False).reset_index(drop=True).head(10)

In [ ]:
# if you want to get the bottom 10, use .tail() e,g

Census_grouped.sort_values(by='Population',ascending=False).reset_index(drop=True).tail(10)

In [ ]:
# the best way to get the bottom values is by using/sorting values in ascending order.then append the head method(),
# then specify the number of values you want.eg the bottom 10  do as follows: .head(10)

Census_grouped.sort_values(by='Population').reset_index(drop=True).head(10)

## WRITE TO AN OUTPUT FILE
#### write to output file using to_filetype() method.we shall write to csv and excel formats
#### this result in a file that has the pandasindex included in the output.
#### to write the files without index,add the index=False parameter.

In [ ]:
# want to get your data back as a file.(very important).want to get  Census_grouped  data as a output file . what you do
# there are many methods depending on the file type you want to get as a result.
# to write the file, saay to_csv() inside the blacket of csv('census.csv')pass the name this 
#file is going to have.eg Census.csv.like follows

Census_grouped.to_csv('census.csv') ## the census file has been created in my working directory. u can open 
                                    #the file/downlod wit excel.the index/labels still appears in our excel file after
                        #downloading and opening the file. to get rid off them,in the to_csv() fuction,pass and argument index 
                                #give it the value False index=false. to _csv(census.csv , index=false ) as follows:
            
Census_grouped.to_csv('census.csv', index=False)

In [ ]:
# to write to other file format,say Census_grouped.to_excel(census.xlsx.index=False )  to excel.


Census_grouped.to_excel('census.xlsx',index=False )

# END OF PANDAS TRAINING.

# DATA VISUALISATION